module.exports = [
    // ---------- Family ----------
    
        { "id": 1, "excuse": "I’ve become a professional couch potato for the day." },
        { "id": 2, "excuse": "My pet goldfish had an emotional breakdown and I had to console it." },
        { "id": 3, "excuse": "I’m in the middle of a deep existential crisis and need time to think." },
        { "id": 4, "excuse": "My Wi-Fi went down, so I couldn't leave the house. Technology was holding me hostage." },
        { "id": 5, "excuse": "I accidentally got sucked into a 6-hour Netflix rabbit hole. It’s too late to escape now." },
        { "id": 6, "excuse": "I had to wash my hair. It was overdue." },
        { "id": 7, "excuse": "I promised my plants I’d spend the day with them. They’re very sensitive." },
        { "id": 8, "excuse": "I was busy re-organizing my sock drawer. It was a mess." },
        { "id": 9, "excuse": "I tried to take a nap and fell into a time vortex. Woke up and hours had passed." },
        { "id": 10, "excuse": "I ran out of excuses, so I made one up." },
        { "id": 11, "excuse": "My phone decided to die at the most inconvenient moment. It’s plotting against me." },
        { "id": 12, "excuse": "I was busy negotiating with my coffee machine. It wasn’t cooperative." },
        { "id": 13, "excuse": "I had to rescue my favorite chair from a dangerous pile of laundry." },
        { "id": 14, "excuse": "I was trying to figure out how to talk to the plants. They don’t respond well to me." },
        { "id": 15, "excuse": "I had to give a motivational speech to my cat. She’s been very lazy lately." },
        { "id": 16, "excuse": "I was busy thinking about all my life choices... and then I forgot." },
        { "id": 17, "excuse": "I got into a heated debate with my reflection. It was a draw." },
        { "id": 18, "excuse": "I had to babysit the TV remote. It was feeling neglected." },
        { "id": 19, "excuse": "I couldn’t find my way out of the internet. It’s more confusing than I thought." },
        { "id": 20, "excuse": "I had to spend the day in silence because my phone was on ‘Do Not Disturb’ mode." },
        { "id": 21, "excuse": "I accidentally became a professional procrastinator today." },
        { "id": 22, "excuse": "I was locked in a room with only snacks and Netflix. It was impossible to leave." },
        { "id": 23, "excuse": "My phone was giving me attitude, and I had to stand my ground." },
        { "id": 24, "excuse": "I had to pet the dog for exactly 3 hours to make sure he felt loved." },
        { "id": 25, "excuse": "I got caught up in an intense staring contest with the wall." },
        { "id": 26, "excuse": "I had to fight an epic battle with a tangled set of headphones." },
        { "id": 27, "excuse": "I had to re-organize my refrigerator. It was starting to look suspicious." },
        { "id": 28, "excuse": "I was trying to figure out how to make the perfect sandwich. It’s harder than it seems." },
        { "id": 29, "excuse": "I was meditating to find inner peace. It didn’t work, but I’m relaxed now." },
        { "id": 30, "excuse": "I tried to do yoga, but I got stuck in a position and couldn’t get out." },
        { "id": 31, "excuse": "I had to help the refrigerator door close. It wasn’t cooperating." },
        { "id": 32, "excuse": "I was making a very important decision: tea or coffee?" },
        { "id": 33, "excuse": "I had to check if the cake I baked was still edible." },
        { "id": 34, "excuse": "I had to check my Facebook status... it was vital." },
        { "id": 35, "excuse": "I had a confrontation with a spoon. It didn’t go well." },
        { "id": 36, "excuse": "I was busy negotiating with the laundry pile. It’s very stubborn." },
        { "id": 37, "excuse": "I was fixing a typo on a webpage. It took longer than I thought." },
        { "id": 38, "excuse": "I had to explain to my bed that I couldn’t stay in it all day." },
        { "id": 39, "excuse": "I got caught in a time loop of scrolling through my phone." },
        { "id": 40, "excuse": "I accidentally stepped into a Netflix binge vortex." },
        { "id": 41, "excuse": "I got lost in a really good book... for several hours." },
        { "id": 42, "excuse": "I was testing the Wi-Fi signal. It’s stronger than I thought." },
        { "id": 43, "excuse": "I had to wrestle with a stubborn jar lid." },
        { "id": 44, "excuse": "I was busy getting into character for a role I’m never going to play." },
        { "id": 45, "excuse": "I had to supervise the oven while my food was cooking. It’s a full-time job." },
        { "id": 46, "excuse": "I was playing detective and investigating the mystery of the missing sock." },
        { "id": 47, "excuse": "I was busy making a vision board, but it wasn’t as inspiring as I thought." },
        { "id": 48, "excuse": "I accidentally broke the space-time continuum by taking a nap." },
        { "id": 49, "excuse": "I was busy finding a new hobby. Turns out, I’m very good at napping." },
        { "id": 50, "excuse": "I had a very important date with the couch and some snacks." },
        { "id": 51, "excuse": "I was just checking on my online shopping orders. You never know when they’ll arrive." },
        { "id": 52, "excuse": "I tried to teach the cat how to use a litter box. It didn’t go well." },
        { "id": 53, "excuse": "I got caught in a heated debate with a potato. It was surprisingly tough." },
        { "id": 54, "excuse": "I was busy discovering new conspiracy theories about socks." },
        { "id": 55, "excuse": "I was too busy trying to figure out how to fold a fitted sheet." },
        { "id": 56, "excuse": "I was in a battle of wills with my alarm clock. It won." },
        { "id": 57, "excuse": "I had to spend some time trying to find the remote... again." },
        { "id": 58, "excuse": "I was busy contemplating life’s biggest question: Is cereal a soup?" },
        { "id": 59, "excuse": "I had to check that my couch was still comfortable. Very important work." },
        { "id": 60, "excuse": "I was investigating the plot twists in my own life. Very complicated." },
        { "id": 61, "excuse": "I was trying to invent a new snack combination. It didn’t turn out as expected." },
        { "id": 62, "excuse": "I was trying to catch up on my dreams. It’s harder than it looks." },
        { "id": 63, "excuse": "I had to argue with a tomato about whether it’s a fruit or a vegetable." },
        { "id": 64, "excuse": "I had to go check on the microwave. It was making suspicious sounds." },
        { "id": 65, "excuse": "I accidentally became a professional napper today." },
        { "id": 66, "excuse": "I was involved in a serious conversation with the Wi-Fi router. It’s complicated." },
        { "id": 67, "excuse": "I got distracted by the sound of my own thoughts." },
        { "id": 68, "excuse": "I had to prepare for an intense staring contest with a lamp." },
        { "id": 69, "excuse": "I got stuck in an online rabbit hole about conspiracy theories involving pigeons." },
        { "id": 70, "excuse": "I had to teach my dog how to fetch. He’s not the brightest." },
        { "id": 71, "excuse": "I was busy mastering the art of procrastination." },
        { "id": 72, "excuse": "I had to adjust my chair, and it took longer than expected." },
        { "id": 73, "excuse": "I had to find a lost sock. It was an emotional journey." },
        { "id": 74, "excuse": "I had to figure out which came first: the chicken or the egg." },
        { "id": 75, "excuse": "I had a one-man show for my plants." },
        { "id": 76, "excuse": "I accidentally overslept, but it was the best sleep of my life." },
        { "id": 77, "excuse": "I was busy reflecting on my life choices while trying to fold a towel." },
        { "id": 78, "excuse": "I needed some alone time with my thoughts. They’re very complicated." },
        { "id": 79, "excuse": "I was busy talking to my refrigerator. It was a very insightful conversation." },
        { "id": 80, "excuse": "I had to ask Google a really important question." },
        { "id": 81, "excuse": "I had to work on my personal growth... or just stare at the wall." },
        { "id": 82, "excuse": "I accidentally became an expert in online shopping." },
        { "id": 83, "excuse": "I was trying to find the perfect angle for a selfie." },
        { "id": 84, "excuse": "I was busy saving the world... one meme at a time." },
        { "id": 85, "excuse": "I had to monitor my food to make sure it wasn’t plotting against me." },
        { "id": 86, "excuse": "I was in the middle of an intense match of rock, paper, scissors with myself." },
        { "id": 87, "excuse": "I was figuring out how to make a sandwich more philosophical." },
        { "id": 88, "excuse": "I needed to take a mental health break... from reality." },
        { "id": 89, "excuse": "I had to teach my dog how to play chess. It’s going well." },
        { "id": 90, "excuse": "I was trying to teach myself how to juggle. It’s a work in progress." },
        { "id": 91, "excuse": "I was busy attempting to break the world record for most snacks eaten in one sitting." },
        { "id": 92, "excuse": "I got distracted watching a squirrel live stream." },
        { "id": 93, "excuse": "I had to check that the earth was still spinning." },
        { "id": 94, "excuse": "I was trying to improve my social media presence. It’s harder than it looks." },
        { "id": 95, "excuse": "I was just having a deep conversation with the fridge." },
        { "id": 96, "excuse": "I was busy making sure the couch didn’t swallow me whole." },
        { "id": 97, "excuse": "I accidentally locked myself out of my own head." },
        { "id": 98, "excuse": "I was busy building a fort out of pillows and blankets." },
        { "id": 99, "excuse": "I got caught in an awkward silence with my own thoughts." },
        { "id": 100, "excuse": "I was busy negotiating with my conscience." },

    // ---------- Office ----------

    { "id": 101, "excuse": "My wife and son were sick and I have to take care of them." },
    { "id": 102, "excuse": "I had to take care of my dog because he is sick." },
    { "id": 103, "excuse": "My mother-in-law passed away." },
    { "id": 104, "excuse": "My wife had to go to the hospital for delivery." },
    { "id": 105, "excuse": "My son had to go to the hospital, he had a bone fracture." },
    { "id": 106, "excuse": "My wife had to go to the hospital for a broken arm." },
    { "id": 107, "excuse": "My son had to go to the hospital for a broken leg." },
    { "id": 108, "excuse": "My parents showed up unannounced at my house." },
    { "id": 109, "excuse": "I got involved in an accident." },
    { "id": 110, "excuse": "Traffic stopped because of a broken truck." },
    { "id": 111, "excuse": "I have a dentist appointment and I cannot reschedule it." },
    { "id": 112, "excuse": "A major delivery is expected today and I need to be in-person to receive it." },
    { "id": 113, "excuse": "I had a family function last night and I am really tired." },
    { "id": 114, "excuse": "My specs broke and I cannot see a thing." },
    { "id": 115, "excuse": "I have come down with a flu due to season change." },
    { "id": 116, "excuse": "I have to attend Parents Teacher meeting for my kids' school" },
    { "id": 117, "excuse": "I've had red eyes since I woke up and I am facing difficulty looking at screens" },
    { "id": 118, "excuse": "The last bus from my house left early and I have no transportation." },
    { "id": 119, "excuse": "I have got work at the bank" },
    { "id": 120, "excuse": "A crime took place in my locality. And police has asked everyone to not leave the premises" },
    { "id": 121, "excuse": "I have a violent cough and I don't want to share it with the rest of my colleagues today." },
    { "id": 122, "excuse": "My car's battery has unfortunately died and I am stranded at home." },
    { "id": 123, "excuse": "I'm feeling burnt out and I need a mental health day." },
    { "id": 124, "excuse": "I promised my aunts that I would meet them this reunion." },
    { "id": 125, "excuse": "My child is having their final dance performance at school and I promised her that I would be there." },
    { "id": 126, "excuse": "The water system at my house is down and I am trying to fix it." },
    { "id": 127, "excuse": "I ate at this seafood place the other day and now my stomach can't stop hurting." },
    { "id": 128, "excuse": "My neck has been stuck in a funny position all morning can I cannot look at the screen properly." },
    { "id": 129, "excuse": "My rabbit just gave birth and I need to make arrangements for 7 more rabbits now." },
    { "id": 130, "excuse": "I have a really, really bad headache." },
    { "id": 131, "excuse": "My Wi-Fi decided it needed a break and now I’m working on 'offline mode'." },
    { "id": 132, "excuse": "I tripped over my own productivity and fell behind today." },
    { "id": 133, "excuse": "The office plants are protesting for more sunlight, and I had to mediate." },
    { "id": 134, "excuse": "I’m stuck in an existential crisis about my lunch choice and it’s taking longer than expected." },
    { "id": 135, "excuse": "My coffee machine broke, and without it, I am unable to function properly." },
    { "id": 136, "excuse": "The printer decided to go on strike, and I couldn’t get any work done without it." },
    { "id": 137, "excuse": "I couldn’t find my way out of my own to-do list this morning." },
    { "id": 138, "excuse": "My stapler staged a walk-out and I had to negotiate a peace treaty." },
    { "id": 139, "excuse": "I was abducted by aliens during my commute, but thankfully they let me go in time." },
    { "id": 140, "excuse": "I got caught in a tug-of-war with my mouse and lost track of time." },
    { "id": 141, "excuse": "I had to save the last donut in the office kitchen from being eaten by the boss." },
    { "id": 142, "excuse": "The coffee machine decided to stop brewing, and I was too tired to do anything without it." },
    { "id": 143, "excuse": "My desk chair started rolling away, and I had to chase it down the hall." },
    { "id": 144, "excuse": "I was locked in the break room by the vending machine and couldn’t escape." },
    { "id": 145, "excuse": "I got distracted by a motivational quote in the hallway and needed time to reflect." },
    { "id": 146, "excuse": "I was trying to teach my computer how to write an email, and it’s taking longer than expected." },
    { "id": 147, "excuse": "I accidentally set my alarm for PM instead of AM, and now I'm running late." },
    { "id": 148, "excuse": "I was engaged in a heated debate with my mouse about which button to click." },
    { "id": 149, "excuse": "I had to step outside and talk to the clouds to understand today's weather forecast better." },
    { "id": 150, "excuse": "I got stuck in a staring contest with the office clock and lost track of time." },
    { "id": 151, "excuse": "I was waiting for my lucky socks to dry before I could start working." },
    { "id": 152, "excuse": "I had to help a colleague find their pen, and it turned into an epic scavenger hunt." },
    { "id": 153, "excuse": "I was trying to decode an email from the boss that looked like it was written in Morse code." },
    { "id": 154, "excuse": "I had to negotiate with the printer because it refused to print anything I asked for." },
    { "id": 155, "excuse": "I had to rescue a rogue paperclip from the bottom of my drawer." },
    { "id": 156, "excuse": "I was busy performing a life-or-death rescue mission for a sticky note that fell off my desk." },
    { "id": 157, "excuse": "The office Wi-Fi went on vacation, and I’m waiting for it to come back." },
    { "id": 158, "excuse": "I had to mediate a feud between my laptop and the office printer. They were not getting along." },
    { "id": 159, "excuse": "My chair is in a protest against sitting too long and refused to let me sit today." },
    { "id": 160, "excuse": "I was trapped in a never-ending loop of 'Are you sure?' pop-up notifications on my computer." },
    { "id": 161, "excuse": "I accidentally spilled coffee on my computer and had to give it a bath before it could work again." },
    { "id": 162, "excuse": "I was busy finding the perfect excuse to call in sick and couldn't get off the phone with myself." },
    { "id": 163, "excuse": "I had a stare-off with my monitor and lost. It's still judging me for taking a break." },
    { "id": 164, "excuse": "The air conditioning is too cold for my creativity to flow, so I had to take a break." },
    { "id": 165, "excuse": "I got distracted by a motivational YouTube video about 'just starting' and now it’s too late." },
    { "id": 166, "excuse": "I had to rescue the last donut in the office kitchen from an unsupervised snack attack." },
    { "id": 167, "excuse": "My cat knocked over my coffee cup and I had to clean up the mess before it became an office emergency." },
    { "id": 168, "excuse": "I got stuck in a heated debate with my reflection about whether I should wear socks or not." },
    { "id": 169, "excuse": "I had a brief moment of enlightenment about work-life balance and needed some time to process it." },
    { "id": 170, "excuse": "I had to attend an emergency Zoom meeting with my house plants. They had some important questions about sunlight." },
    { "id": 171, "excuse": "The printer decided to go on vacation and didn’t leave a forwarding address." },
    { "id": 172, "excuse": "I had to spend the morning convincing my stapler to cooperate, and it was not easy." },
    { "id": 173, "excuse": "I found myself locked in the break room with a sandwich, and it was a hard decision whether to eat or work." },
    { "id": 174, "excuse": "I got into a heated discussion about the best way to organize office supplies and it took longer than expected." },
    { "id": 175, "excuse": "I had to teach my computer how to stop autocorrecting my words to 'duck'." },
    { "id": 176, "excuse": "I had to explain to my printer why it couldn’t print the office’s wishes for World Peace." },
    { "id": 177, "excuse": "I accidentally hit 'Reply All' on an email, and now I’m in an office-wide debate about lunch options." },
    { "id": 178, "excuse": "I had to stop and meditate because my coffee mug was looking at me judgmentally." },
    { "id": 179, "excuse": "My computer froze during the most important moment of my virtual meeting and refused to unfreeze." },
    { "id": 180, "excuse": "I had to convince my chair to stop swiveling so much before it became an HR issue." },
    { "id": 181, "excuse": "I tried to set up a new desk arrangement, but the chairs went on strike." },
    { "id": 182, "excuse": "The elevator decided to have a philosophical moment about whether it should go up or down." },
    { "id": 183, "excuse": "I had to break up a serious argument between my mouse and keyboard over control of the cursor." },
    { "id": 184, "excuse": "My monitor was trying to send me cryptic messages and I had to decipher them first." },
    { "id": 185, "excuse": "I got caught in a traffic jam caused by an office chair convention." },
    { "id": 186, "excuse": "I had to babysit my coffee cup because it kept getting stolen from my desk." },
    { "id": 187, "excuse": "My mouse was refusing to cooperate and went on an unsanctioned walk around the office." },
    { "id": 188, "excuse": "I had to step outside and apologize to the sun for not appreciating it enough." },
    { "id": 189, "excuse": "I had a staring contest with my inbox, and it won, so I had to regroup." },
    { "id": 190, "excuse": "I was busy putting my plants on a meeting schedule so they can attend work-life balance seminars too." },
    { "id": 191, "excuse": "My coffee cup kept yelling at me, and I had to have a serious conversation about boundaries." },
    { "id": 192, "excuse": "I had to troubleshoot why the photocopier was acting like it was auditioning for a role in a horror movie." },
    { "id": 193, "excuse": "I was busy convincing my desk lamp that it’s time to shine brighter." },
    { "id": 194, "excuse": "My mouse pad went missing, and I had to send out a search party for it." },
    { "id": 195, "excuse": "I had to explain to my monitor why I wasn’t ready for a full-screen experience just yet." },
    { "id": 196, "excuse": "My lunch decided to take over my desk, and I had to negotiate a peace treaty with it." },
    { "id": 197, "excuse": "I had to teach my keyboard to stop typing random letters when I wasn’t looking." },
    { "id": 198, "excuse": "I accidentally summoned a meeting by pressing the wrong keyboard shortcut." },
    { "id": 199, "excuse": "I was busy answering my pet fish's philosophical questions about water." },
    { "id": 200, "excuse": "My desk chair suddenly rolled away from me and I spent the morning chasing it around the office." },


    // ---------- College ----------

    { "id": 201, "excuse": "I was stuck in a time loop trying to relive last semester's best moments." },
    { "id": 202, "excuse": "The library trapped me in the Philosophy section, and I couldn't find my way out." },
    { "id": 203, "excuse": "My alarm clock decided it was finally time to rebel and turned itself off." },
    { "id": 204, "excuse": "I accidentally joined the wrong lecture and didn't realize until the end." },
    { "id": 205, "excuse": "My pen ran out of ink during an important assignment, and I had to perform a eulogy." },
    { "id": 206, "excuse": "I got locked in the cafeteria while taste-testing all the desserts." },
    { "id": 207, "excuse": "I couldn't decide which shoes to wear and missed the bus while overthinking." },
    { "id": 208, "excuse": "I was conducting a highly scientific experiment to see how long I could nap." },
    { "id": 209, "excuse": "My laptop started speaking in binary, and I had to translate everything." },
    { "id": 210, "excuse": "I was busy calculating how many naps equal a good night's sleep." },
    { "id": 211, "excuse": "My group project turned into an escape room, and no one found the exit." },
    { "id": 212, "excuse": "The campus squirrels demanded a meeting to discuss their rights." },
    { "id": 213, "excuse": "I forgot my notes and had to re-watch all the lectures at double speed." },
    { "id": 214, "excuse": "My roommate's karaoke session was so intense that I had to supervise." },
    { "id": 215, "excuse": "I was busy auditioning for the role of ‘most stressed student’ and lost track of time." },
    { "id": 216, "excuse": "I accidentally spilled coffee on my only copy of the assignment and had to rewrite it." },
    { "id": 217, "excuse": "My backpack went missing, and it took me an hour to realize it was still on my back." },
    { "id": 218, "excuse": "I had a staring contest with my whiteboard notes and got too invested." },
    { "id": 219, "excuse": "I tried to microwave my coffee, and the microwave decided to quit on me." },
    { "id": 220, "excuse": "I accidentally fell into a Wikipedia rabbit hole while researching a single topic." },
    { "id": 221, "excuse": "My phone's calendar told me the wrong date, and I trusted it blindly." },
    { "id": 222, "excuse": "The campus vending machine held my snacks hostage, and I had to negotiate." },
    { "id": 223, "excuse": "I couldn't find my lucky pen, and it felt like academic betrayal." },
    { "id": 224, "excuse": "I had to comfort my roommate after they lost a crucial match in Mario Kart." },
    { "id": 225, "excuse": "I got distracted trying to solve a Rubik's cube and missed everything else." },
    { "id": 226, "excuse": "My bike chain broke, and I had to channel my inner mechanic to fix it." },
    { "id": 227, "excuse": "I accidentally printed my assignment on sticky notes and had to fix it." },
    { "id": 228, "excuse": "I was busy helping my friend rehearse for their dramatic apology to their crush." },
    { "id": 229, "excuse": "I spilled water on my desk and spent an hour rearranging everything." },
    { "id": 230, "excuse": "My pet goldfish gave me the side-eye, and I had to figure out what I did wrong." },
    { "id": 231, "excuse": "I spent the morning tracking down who ‘borrowed’ my textbook and forgot to return it." },
    { "id": 232, "excuse": "I got sidetracked while trying to write a motivational quote for my notebook cover." },
    { "id": 233, "excuse": "My shoes had an identity crisis and decided to squeak with every step." },
    { "id": 234, "excuse": "I was practicing my signature for when I’m famous, and time flew by." },
    { "id": 235, "excuse": "I got caught in a heated debate with myself over which highlighter color to use." },
    { "id": 236, "excuse": "The printer jammed, and I had to perform open-printer surgery." },
    { "id": 237, "excuse": "I got caught up explaining a meme to my study group and forgot the time." },
    { "id": 238, "excuse": "I accidentally wrote my notes in invisible ink and had to start over." },
    { "id": 239, "excuse": "I spilled my entire breakfast on my project and had to clean up the mess." },
    { "id": 240, "excuse": "My alarm got jealous of my sleep and decided not to wake me up." },
    { "id": 241, "excuse": "I spent 30 minutes trying to figure out where I left my glasses, only to realize they were on my head." },
    { "id": 242, "excuse": "I got lost on the way to class because my GPS insisted on 'taking the scenic route'." },
    { "id": 243, "excuse": "My laptop decided to install updates at the worst possible moment." },
    { "id": 244, "excuse": "I got locked out of my dorm room while chasing after a rogue sock." },
    { "id": 245, "excuse": "I had to help my friend practice their 'I'm sorry' speech for an overdue assignment." },
    { "id": 246, "excuse": "My umbrella turned inside out during a storm, and it took a while to recover." },
    { "id": 247, "excuse": "The campus Wi-Fi went on strike, and I spent the morning troubleshooting it." },
    { "id": 248, "excuse": "I accidentally packed my roommate's notes instead of mine and had to track them down." },
    { "id": 249, "excuse": "I got stuck in a line for coffee because the barista was crafting a masterpiece latte." },
    { "id": 250, "excuse": "I misread the schedule and showed up to the wrong class entirely." },
    { "id": 251, "excuse": "I was stuck debating whether my handwriting is art or a crime scene." },
    { "id": 252, "excuse": "My pen decided to leak everywhere except on my assignment." },
    { "id": 253, "excuse": "I got caught in the rain while trying to save my notes, and the notes didn’t survive." },
    { "id": 254, "excuse": "My brain was buffering, and I couldn't load the required knowledge in time." },
    { "id": 255, "excuse": "I accidentally overslept while dreaming about attending class on time." },
    { "id": 256, "excuse": "I spent the morning untangling my headphones and questioning my life choices." },
    { "id": 257, "excuse": "I had to rescue my assignment from a surprise gust of wind." },
    { "id": 258, "excuse": "I found a squirrel in my backpack and had to convince it to leave." },
    { "id": 259, "excuse": "I got locked out of the lecture hall because I forgot my ID card." },
    { "id": 260, "excuse": "My water bottle decided to leak all over my notes, so I had to rewrite them." },
    { "id": 261, "excuse": "I accidentally joined a campus protest thinking it was a class discussion." },
    { "id": 262, "excuse": "My laundry took longer than expected because the dryer decided to nap." },
    { "id": 263, "excuse": "I tried to take a shortcut through the library and got lost in the stacks." },
    { "id": 264, "excuse": "My backpack zipper broke, and everything fell out in the middle of the hallway." },
    { "id": 265, "excuse": "I got stuck helping a campus bird untangle itself from a bench." },
    { "id": 266, "excuse": "I accidentally spilled hot coffee on myself and had to do emergency cleanup." },
    { "id": 267, "excuse": "I had to wait for maintenance because my dorm door wouldn’t open." },
    { "id": 268, "excuse": "I got distracted organizing my stationery collection and lost track of time." },
    { "id": 269, "excuse": "I was chasing a campus bus that decided to leave early." },
    { "id": 270, "excuse": "My classmate borrowed my calculator and disappeared into the void." },
    { "id": 271, "excuse": "I got stuck explaining my project to a very curious janitor." },
    { "id": 272, "excuse": "I missed my alarm because I set it to PM instead of AM." },
    { "id": 273, "excuse": "I was perfecting my ‘I totally understand this’ face in front of the mirror." },
    { "id": 274, "excuse": "My umbrella turned traitor and flipped inside out during a windstorm." },
    { "id": 275, "excuse": "My roommate started a breakfast feast, and I got drafted as the sous-chef." },
    { "id": 276, "excuse": "I accidentally left my notes on the campus bus and had to track them down." },
    { "id": 277, "excuse": "My shoestrings snapped, and I had to perform emergency repairs." },
    { "id": 278, "excuse": "The vending machine ate my money, so I had to stage a rescue mission for my snack." },
    { "id": 279, "excuse": "I got distracted trying to help a lost freshman find their way." },
    { "id": 280, "excuse": "I got caught up editing my essay because I suddenly hated every word I wrote." },
    { "id": 281, "excuse": "My umbrella was in a fight with the wind, and I had to referee." },
    { "id": 282, "excuse": "My favorite coffee shop was out of my go-to drink, and I had to find an alternative." },
    { "id": 283, "excuse": "I had to rescue my laptop from a coffee spill during a study session." },
    { "id": 284, "excuse": "I got stuck deciphering my own handwriting from last night’s notes." },
    { "id": 285, "excuse": "I lost my phone in my backpack and spent 30 minutes trying to find it." },
    { "id": 286, "excuse": "My printer ran out of ink, and I had to run across campus to print my assignment." },
    { "id": 287, "excuse": "I got sidetracked trying to fix a PowerPoint animation that wouldn’t cooperate." },
    { "id": 288, "excuse": "I accidentally dropped my wallet in a puddle and had to dry everything out." },
    { "id": 289, "excuse": "I had to untangle my charger from the bottomless pit of my backpack." },
    { "id": 290, "excuse": "I got caught up in a discussion about campus squirrels and their secret lives." },
    { "id": 291, "excuse": "I accidentally spilled granola in my laptop keyboard and had to clean it out." },
    { "id": 292, "excuse": "My coffee thermos broke, and I had to find a replacement for my caffeine fix." },
    { "id": 293, "excuse": "My shoelaces got caught in an escalator, and it took ages to free them." },
    { "id": 294, "excuse": "I had to babysit my roommate’s pet fish while they attended a group meeting." },
    { "id": 295, "excuse": "I spilled soda on my backpack and had to wash everything inside." },
    { "id": 296, "excuse": "My phone’s weather app betrayed me, and I got caught in an unexpected rainstorm." },
    { "id": 297, "excuse": "I got lost trying to find the new classroom because the campus map was wrong." },
    { "id": 298, "excuse": "I accidentally walked into the wrong lecture and stayed because I was too embarrassed to leave." },
    { "id": 299, "excuse": "I got locked out of the dorm because my keycard stopped working." },
    { "id": 300, "excuse": "I spent the morning rescuing my group project from disappearing into a black hole of procrastination." },

    // ---------- Party ----------

        { "id": 301, "excuse": "I accidentally ate too much and now I’m glued to my couch." },
        { "id": 302, "excuse": "My pajamas have declared a protest and won’t let me change into party clothes." },
        { "id": 303, "excuse": "I just started a movie marathon, and I can’t abandon my couch mid-battle scene." },
        { "id": 304, "excuse": "I opened a bag of chips and now I’m morally obligated to finish them all." },
        { "id": 305, "excuse": "I forgot to feed my imaginary pet, and now it’s throwing a tantrum." },
        { "id": 306, "excuse": "I accidentally locked myself in my apartment because my key is on the other side of the door." },
        { "id": 307, "excuse": "I promised my plants I’d spend quality time with them, and I can’t break their trust." },
        { "id": 308, "excuse": "I started organizing my sock drawer, and now I have to see it through." },
        { "id": 309, "excuse": "My favorite TV show is airing tonight, and I can’t betray it by going to a party." },
        { "id": 310, "excuse": "I spilled coffee on my only party outfit, and now I have nothing to wear." },
        { "id": 311, "excuse": "My neighbors are throwing a louder party, and I got stuck mediating the noise war." },
        { "id": 312, "excuse": "I got emotionally invested in a book and now can’t leave until I finish it." },
        { "id": 313, "excuse": "My cat is sitting on my lap, and I can’t move without breaking the unspoken rule of cats." },
        { "id": 314, "excuse": "I tried to bake something for the party, and now my oven won’t stop smoking." },
        { "id": 315, "excuse": "I stubbed my toe so hard that walking feels like an Olympic event." },
        { "id": 316, "excuse": "I accidentally put my phone on airplane mode and missed the party details." },
        { "id": 317, "excuse": "I started binge-watching a true crime series and need to know who did it before I can leave." },
        { "id": 318, "excuse": "I spilled glitter on my carpet, and now my entire apartment looks like a disco ball." },
        { "id": 319, "excuse": "I misplaced my shoes, and without them, I’m legally not allowed to attend parties." },
        { "id": 320, "excuse": "I decided to deep clean my fridge, and now I’m emotionally invested in expired yogurt." },
        { "id": 321, "excuse": "My dog gave me sad eyes, and now I’m guilted into staying home." },
        { "id": 322, "excuse": "My introvert battery died, and I need to recharge it with silence and snacks." },
        { "id": 323, "excuse": "I accidentally fell asleep, and my bed has trapped me with its warmth." },
        { "id": 324, "excuse": "I got caught up sewing a button on my shirt and accidentally made a scarf instead." },
        { "id": 325, "excuse": "I started a jigsaw puzzle, and now I’m determined to find the corner pieces." },
        { "id": 326, "excuse": "I burnt my dinner and now have to mourn its loss before I can socialize." },
        { "id": 327, "excuse": "I opened my junk drawer, and now I’m stuck sorting random batteries and rubber bands." },
        { "id": 328, "excuse": "I got caught up watching conspiracy theories and now fear leaving my house." },
        { "id": 329, "excuse": "My socks don’t match, and it’s throwing off my entire vibe for the evening." },
        { "id": 330, "excuse": "I accidentally started painting, and now my hands are covered in colors." },
        { "id": 331, "excuse": "I ran out of snacks and can’t attend a party empty-handed." },
        { "id": 332, "excuse": "I’m stuck contemplating life because my Wi-Fi stopped working for five minutes." },
        { "id": 333, "excuse": "My microwave started making weird noises, and now I’m afraid to leave it alone." },
        { "id": 334, "excuse": "I opened my closet and got buried under a pile of unfolded clothes." },
        { "id": 335, "excuse": "I got caught in a staring contest with my pet fish and lost track of time." },
        { "id": 336, "excuse": "I tried to take a quick nap and accidentally traveled to another dimension of sleep." },
        { "id": 337, "excuse": "I started knitting a scarf, and now I’m halfway to making a blanket." },
        { "id": 338, "excuse": "I realized I forgot to do laundry, and now my favorite outfit is unavailable." },
        { "id": 339, "excuse": "I accidentally broke my phone charger, and now I’m waiting for it to fix itself." },
        { "id": 340, "excuse": "I dropped my contact lenses, and now I’m crawling on the floor looking for them." },
        { "id": 341, "excuse": "I burnt my popcorn and now have to detox my apartment from the smell." },
        { "id": 342, "excuse": "My neighbors started karaoke night, and now I’m forced to endure it." },
        { "id": 343, "excuse": "I accidentally signed up for an online course and now feel guilty for not attending it." },
        { "id": 344, "excuse": "My favorite mug broke, and I’m in mourning." },
        { "id": 345, "excuse": "I realized I’m an adult and chose to embrace doing nothing tonight." },
        { "id": 346, "excuse": "My refrigerator light went out, and now I’m stuck wondering what’s inside." },
        { "id": 347, "excuse": "I was doing yoga and accidentally meditated myself into staying home." },
        { "id": 348, "excuse": "My playlist wasn’t working, and I can’t party without the perfect music vibes." },
        { "id": 349, "excuse": "I misplaced my glasses, and everything looks blurry, including the decision to party." },
        { "id": 350, "excuse": "I had a deep philosophical conversation with my microwave about leftovers." },
        { "id": 351, "excuse": "I ran out of toothpaste and didn’t feel presentable enough to party." },
        { "id": 352, "excuse": "I realized the moon was full and decided to howl at it from my balcony instead." },
        { "id": 353, "excuse": "I was trying to write a poem and got caught up in rhymes about avoiding parties." },
        { "id": 354, "excuse": "I spilled soup on my floor and had to reenact Cinderella to clean it up." },
        { "id": 355, "excuse": "I started a solo dance party at home and didn’t want to stop the vibe." },
        { "id": 356, "excuse": "My horoscope told me today was a bad day for socializing." },
        { "id": 357, "excuse": "I misplaced my wallet and am currently hunting it down like a treasure map." },
        { "id": 358, "excuse": "I accidentally turned off my phone and took it as a sign from the universe to stay home." },
        { "id": 359, "excuse": "I was busy googling how to gracefully avoid parties." },
        { "id": 360, "excuse": "I tried a new recipe and ended up setting off the smoke alarm." },
        { "id": 361, "excuse": "I got stuck in my own head thinking about what to wear, so I stayed home instead." },
        { "id": 362, "excuse": "My ceiling fan was making strange noises, and I couldn’t leave it unsupervised." },
        { "id": 363, "excuse": "I got distracted watching cat videos and lost track of time." },
        { "id": 364, "excuse": "I accidentally started journaling and couldn’t stop writing my life story." },
        { "id": 365, "excuse": "I ran out of coffee, and I can’t function without caffeine." },
        { "id": 366, "excuse": "I forgot to RSVP, and now I feel like an uninvited ghost." },
        { "id": 367, "excuse": "I started redecorating my room and accidentally turned it into a construction zone." },
        { "id": 368, "excuse": "I tried on my party outfit and realized it doesn’t fit anymore." },
        { "id": 369, "excuse": "I got stuck doing a personality quiz online, trying to figure out which fruit I am." },
        { "id": 370, "excuse": "I opened a bag of popcorn and accidentally ate it all by myself." },
        { "id": 371, "excuse": "I started cleaning my windows and got emotionally invested in removing streaks." },
        { "id": 372, "excuse": "I realized I don’t like anyone at the party enough to attend." },
        { "id": 373, "excuse": "I decided to write a song about avoiding parties and got stuck on the chorus." },
        { "id": 374, "excuse": "I tried to put on makeup but poked my eye with mascara and had to recover." },
        { "id": 375, "excuse": "My alarm clock went off, and I took it as a sign to nap instead of party." },
        { "id": 376, "excuse": "I started folding my laundry and got stuck making the perfect towel stack." },
        { "id": 377, "excuse": "I had a minor existential crisis about why parties even exist." },
        { "id": 378, "excuse": "I decided to stay home and play my favorite board game solo." },
        { "id": 379, "excuse": "I spilled juice on my carpet, and now I’m stuck scrubbing it out." },
        { "id": 380, "excuse": "I couldn’t decide which shoes to wear, so I gave up entirely." },
        { "id": 381, "excuse": "I got lost in thought about whether pineapples belong on pizza." },
        { "id": 382, "excuse": "I accidentally started a DIY project and can’t leave it unfinished." },
        { "id": 383, "excuse": "I tried to cut my own bangs and now can’t show my face in public." },
        { "id": 384, "excuse": "I realized my dog has better social skills than I do, so I stayed home." },
        { "id": 385, "excuse": "I lit a candle and got mesmerized by the flame, forgetting all about the party." },
        { "id": 386, "excuse": "I lost my keys and spent the entire evening turning my place upside down." },
        { "id": 387, "excuse": "I put on my shoes and realized I wasn’t ready to face people." },
        { "id": 388, "excuse": "I got caught up trying to solve a Rubik’s Cube." },
        { "id": 389, "excuse": "I decided to reorganize my bookshelf by color and got carried away." },
        { "id": 390, "excuse": "I started learning to juggle and lost track of time." },
        { "id": 391, "excuse": "I baked cookies for the party but ended up eating them all." },
        { "id": 392, "excuse": "I spilled ketchup on my shirt and have no time to change." },
        { "id": 393, "excuse": "I forgot how to socialize and decided to stay in." },
        { "id": 394, "excuse": "I accidentally broke my phone screen while deciding whether to text back." },
        { "id": 395, "excuse": "I realized I have nothing interesting to say, so I stayed home to ponder." },
        { "id": 396, "excuse": "I got stuck trying to assemble a piece of IKEA furniture." },
        { "id": 397, "excuse": "I accidentally knocked over my houseplant and had to re-pot it." },
        { "id": 398, "excuse": "I couldn’t decide if I wanted to go, so I stayed home by default." },
        { "id": 399, "excuse": "I started doodling and created an accidental masterpiece that I couldn’t leave unfinished." },
        { "id": 400, "excuse": "I looked at the clock, realized I’m an adult, and chose Netflix instead." },

    //---------Funny---------

        { "id": 401, "excuse": "I was convinced my couch was holding me hostage for a Netflix marathon." },
        { "id": 402, "excuse": "I accidentally started alphabetizing my spice rack and couldn’t stop." },
        { "id": 403, "excuse": "My left sock disappeared, and I spent the day searching for it." },
        { "id": 404, "excuse": "I found a recipe for a cake and ended up baking cookies instead." },
        { "id": 405, "excuse": "I heard a strange noise in my house and spent hours investigating like a detective." },
        { "id": 406, "excuse": "I put my phone on silent and forgot where I left it." },
        { "id": 407, "excuse": "I tried to iron my clothes but ended up ironing the carpet instead." },
        { "id": 408, "excuse": "I was waiting for a parcel delivery and couldn’t risk missing it." },
        { "id": 409, "excuse": "I started a new book and couldn’t put it down until I finished it." },
        { "id": 410, "excuse": "I found my childhood diary and got stuck reminiscing for hours." },
        { "id": 411, "excuse": "I misplaced my favorite hat and had to conduct a full house search." },
        { "id": 412, "excuse": "I got caught up explaining quantum physics to my pet goldfish." },
        { "id": 413, "excuse": "I accidentally painted my nails and couldn’t leave until they dried." },
        { "id": 414, "excuse": "I stepped in gum and spent hours trying to clean my shoe." },
        { "id": 415, "excuse": "I lost the TV remote and ended up binge-watching the weather channel." },
        { "id": 416, "excuse": "I started journaling and ended up writing a novel about avoiding parties." },
        { "id": 417, "excuse": "My ceiling fan was making weird noises, and I couldn’t trust it alone." },
        { "id": 418, "excuse": "I opened my junk drawer and fell into the abyss of forgotten treasures." },
        { "id": 419, "excuse": "I spilled glitter everywhere and spent the evening looking like a disco ball." },
        { "id": 420, "excuse": "I realized I didn’t have anything to wear and gave up on going out." },
        { "id": 421, "excuse": "I found an old jigsaw puzzle and got obsessed with finding the edge pieces." },
        { "id": 422, "excuse": "I started a solo karaoke session and couldn’t stop singing off-key hits." },
        { "id": 423, "excuse": "I accidentally cooked a five-course meal and had to taste everything." },
        { "id": 424, "excuse": "I tried to open a jar of pickles and ended up stuck with a bruised hand." },
        { "id": 425, "excuse": "I got lost in a YouTube rabbit hole about penguins." },
        { "id": 426, "excuse": "I spilled coffee on my keyboard and spent hours cleaning sticky keys." },
        { "id": 427, "excuse": "I realized my socks didn’t match, and it threw off my whole vibe." },
        { "id": 428, "excuse": "I accidentally downloaded a meditation app and got lost in mindful breathing." },
        { "id": 429, "excuse": "I opened a bag of chips and felt morally obligated to finish them all." },
        { "id": 430, "excuse": "My pet needed extra cuddles, and I couldn’t disappoint them." },
        { "id": 431, "excuse": "I burnt my popcorn and couldn’t leave until the smell disappeared." },
        { "id": 432, "excuse": "I found an old mixtape and spent hours rediscovering my teenage angst." },
        { "id": 433, "excuse": "I accidentally locked myself out of my own house and had to wait for a locksmith." },
        { "id": 434, "excuse": "I started painting and ended up with more paint on me than the canvas." },
        { "id": 435, "excuse": "I discovered a new conspiracy theory and couldn’t stop researching it." },
        { "id": 436, "excuse": "I got distracted trying to assemble IKEA furniture without the instructions." },
        { "id": 437, "excuse": "I started folding laundry and turned it into a precision art project." },
        { "id": 438, "excuse": "I tripped over my own shoes and decided it was safer to stay home." },
        { "id": 439, "excuse": "I spilled juice on my favorite shirt and couldn’t find a backup outfit." },
        { "id": 440, "excuse": "I realized the party clashed with my scheduled nap time." },
        { "id": 441, "excuse": "I accidentally vacuumed up an important receipt and spent hours retrieving it." },
        { "id": 442, "excuse": "I started knitting and couldn’t stop until I finished the scarf." },
        { "id": 443, "excuse": "I misplaced my car keys and had to conduct a full-scale search." },
        { "id": 444, "excuse": "I got caught up organizing my digital photo library." },
        { "id": 445, "excuse": "I realized I’m terrible at small talk and decided to avoid awkward moments." },
        { "id": 446, "excuse": "I found an old board game and spent the evening trying to beat myself." },
        { "id": 447, "excuse": "I dropped my contact lenses and spent hours crawling on the floor." },
        { "id": 448, "excuse": "I started journaling my goals and accidentally planned the next ten years." },
        { "id": 449, "excuse": "I spilled water on my party shoes and had nothing else to wear." },
        { "id": 450, "excuse": "I got mesmerized by my lava lamp and lost track of time." },
        { "id": 451, "excuse": "I burnt my dinner and spent the evening airing out my kitchen." },
        { "id": 452, "excuse": "I got caught in a loop of rewatching my favorite sitcom." },
        { "id": 453, "excuse": "I started decluttering my closet and ended up making a bigger mess." },
        { "id": 454, "excuse": "I had an intense debate with myself about whether pineapple belongs on pizza." },
        { "id": 455, "excuse": "I tried on my old jeans and got stuck trying to wiggle out of them." },
        { "id": 456, "excuse": "I spilled milk and spent hours cleaning my floor and existential crisis." },
        { "id": 457, "excuse": "I got lost in a book about time travel and forgot what year it was." },
        { "id": 458, "excuse": "I discovered an old video game and couldn’t put it down." },
        { "id": 459, "excuse": "I found my old karaoke machine and couldn’t resist singing." },
        { "id": 460, "excuse": "I got distracted by a puzzle and couldn’t stop until I found all the pieces." },
        { "id": 461, "excuse": "I started cleaning my fish tank and lost track of time." },
        { "id": 462, "excuse": "I found an old diary and got sucked into my teenage memories." },
        { "id": 463, "excuse": "I realized I’m an adult and chose to enjoy my solitude." },
        { "id": 464, "excuse": "I spilled coffee on my favorite book and had to carefully save every page." },
        { "id": 465, "excuse": "I accidentally joined an online cooking class and had to finish the recipe." },
        { "id": 466, "excuse": "I got stuck in a YouTube rabbit hole about cute animal videos." },
        { "id": 467, "excuse": "I accidentally locked myself in the bathroom and had to wait for rescue." },
        { "id": 468, "excuse": "I got mesmerized by the rain and spent hours staring out my window." },
        { "id": 469, "excuse": "I started fixing my bicycle and ended up disassembling it completely." },
        { "id": 470, "excuse": "I started organizing my sock drawer and found mismatches that needed solving." },
        { "id": 471, "excuse": "I tripped over a shoe and spent the evening questioning my coordination." },
        { "id": 472, "excuse": "I spilled soup and had to deep clean my entire kitchen." },
        { "id": 473, "excuse": "I started a new hobby and couldn’t stop until I mastered it." },
        { "id": 474, "excuse": "I accidentally got paint on my clothes and spent hours trying to clean it." },
        { "id": 475, "excuse": "I discovered a leak in my roof and had to fix it immediately." },
        { "id": 476, "excuse": "I misplaced my wallet and couldn’t leave the house without it." },
        { "id": 477, "excuse": "I got stuck in traffic caused by a parade of geese crossing the road." },
        { "id": 478, "excuse": "I got caught in a crossword puzzle marathon and couldn’t leave." },
        { "id": 479, "excuse": "I accidentally dyed my hair green and couldn’t face the public yet." },
        { "id": 480, "excuse": "I got stuck watching a documentary and couldn’t leave without knowing the ending." },
        { "id": 481, "excuse": "I accidentally joined an online quiz and had to finish the game." },
        { "id": 482, "excuse": "I got stuck in a maze trying to find the nearest grocery store." },
        { "id": 483, "excuse": "I accidentally spilled glitter everywhere and spent hours cleaning up the sparkles." },
        { "id": 484, "excuse": "I started a puzzle and refused to leave until it was complete." },
        { "id": 485, "excuse": "I was locked out of my house and had to wait for the locksmith." },
        { "id": 486, "excuse": "I lost my favorite pen and spent the day looking for it." },
        { "id": 487, "excuse": "I got caught up in organizing my bookshelf and couldn’t stop until it was perfect." },
        { "id": 488, "excuse": "I got stuck cleaning my fridge after accidentally spilling milk." },
        { "id": 489, "excuse": "I got lost in a fantasy world after starting a new novel." },
        { "id": 490, "excuse": "I was baking cookies and burnt the first batch, had to retry." },
        { "id": 491, "excuse": "I misplaced my favorite shoes and couldn’t go out without them." },
        { "id": 492, "excuse": "I got locked inside my apartment and had to call for help." },
        { "id": 493, "excuse": "I spilled juice on my party outfit and had nothing else to wear." },
        { "id": 494, "excuse": "I accidentally got into a marathon of cleaning my house." },
        { "id": 495, "excuse": "I started coloring in a book and couldn’t stop until it was done." },
        { "id": 496, "excuse": "I found an old music playlist and spent hours reliving the songs." },
        { "id": 497, "excuse": "I discovered a spider in my house and had to deal with it." },
        { "id": 498, "excuse": "I got caught up knitting a scarf for my pet." },
        { "id": 499, "excuse": "I misplaced my keys and couldn’t find them for hours." },
        { "id": 500, "excuse": "I got caught up playing a game and couldn’t pause it." },

    //----------Unbelievable Excuses----------

    { "id": 501, "excuse": "I had a fever the next day." },
    { "id": 502, "excuse": "My car radio was broken, and I couldn't drive if I didn't have music." },
    { "id": 503, "excuse": "I heard there will be a thunderstorm today." },
    { "id": 504, "excuse": "The alarm betrayed me today." },
    { "id": 505, "excuse": "I was passing by a school lane so I was driving slow." },
    { "id": 506, "excuse": "I had visitors at home!" },
    { "id": 507, "excuse": "Her hair dryer was shorted out so she needed to wait till her hair was dry." },
    { "id": 508, "excuse": "Clothes were dirty today, so I did laundry work first." },
    { "id": 509, "excuse": "A cat crossed my path." },
    { "id": 510, "excuse": "I was by mistake locked inside the house, so took help from neighbours." },
    { "id": 511, "excuse": "I was riding my solar power scooter and suddenly it started raining and my scooter stopped working." },
    { "id": 512, "excuse": "The left signal of my car was not working, so I only took right to reach to the office." },
    { "id": 513, "excuse": "I saw a firetruck on my way so I had a doubt and to clarify I went back home to check." },
    { "id": 514, "excuse": "I saw many strangers following my car so I took the longest route possible to reach today." },
    { "id": 515, "excuse": "My trimmer stopped working yesterday and yesterday It was Monday." },
    { "id": 516, "excuse": "I drove to the previous employer yesterday." },
    { "id": 517, "excuse": "I had to take my goldfish for a walk." },
    { "id": 518, "excuse": "My washing machine was acting up and I had to negotiate with it." },
    { "id": 519, "excuse": "I had a staring contest with my reflection and I lost." },
    { "id": 520, "excuse": "I was trying to cook dinner, but the recipe was a complete disaster." },
    { "id": 521, "excuse": "My refrigerator ran away with my leftovers." },
    { "id": 522, "excuse": "I had to wait for the paint on my house to dry." },
    { "id": 523, "excuse": "I tried to set up a hammock in my living room, but it turned into a wrestling match." },
    { "id": 524, "excuse": "My pet parrot convinced me to stay home and binge-watch Netflix." },
    { "id": 525, "excuse": "I tried to pet my neighbor's dog, but it ran away with my shoes." },
    { "id": 526, "excuse": "I spilled a drink on my calendar and had to wait for it to dry." },
    { "id": 527, "excuse": "I was trapped in an endless loop of reboots with my computer." },
    { "id": 528, "excuse": "I had to readjust my entire wardrobe because I had a closet emergency." },
    { "id": 529, "excuse": "I mistook my phone charger for a snake and had to calm myself down." },
    { "id": 530, "excuse": "I got distracted by an impromptu karaoke session in the living room." },
    { "id": 531, "excuse": "I tried to wash my car, but it started raining harder than I could handle." },
    { "id": 532, "excuse": "My socks went missing, and I spent the day searching for them." },
    { "id": 533, "excuse": "My plants needed me to meditate with them before they could be watered." },
    { "id": 534, "excuse": "I ran into a neighbor and ended up in a 2-hour conversation about the best pizza toppings." },
    { "id": 535, "excuse": "I thought it was Sunday, so I was just relaxing at home." },
    { "id": 536, "excuse": "I was busy trying to teach my dog how to play chess." },
    { "id": 537, "excuse": "My dishwasher was going on strike, so I had to negotiate with it." },
    { "id": 538, "excuse": "I had to take my shoes to the cobbler for an emergency fix." },
    { "id": 539, "excuse": "My internet was down, and I couldn't connect to anything, even reality." },
    { "id": 540, "excuse": "I couldn't find my keys, and I had to retrace my steps all the way to the store." },
    { "id": 541, "excuse": "I was trying to finish a puzzle, but the pieces were conspiring against me." },
    { "id": 542, "excuse": "My cat wanted to have a meeting about my schedule before I could leave." },
    { "id": 543, "excuse": "I had to stand in front of a mirror to practice my best ‘Sorry I’m late’ face." },
    { "id": 544, "excuse": "I got distracted by a squirrel on my way out." },
    { "id": 545, "excuse": "I had to teach my phone how to properly autocorrect." },
    { "id": 546, "excuse": "I couldn't leave because I was too busy contemplating the meaning of life." },
    { "id": 547, "excuse": "I got stuck in a traffic jam caused by a parade of baby strollers." },
    { "id": 548, "excuse": "I was busy counting the clouds to see if they matched my mood." },
    { "id": 549, "excuse": "I had to wait for my shoes to dry after walking through a puddle." },
    { "id": 550, "excuse": "I was giving my plants a motivational speech." },
    { "id": 551, "excuse": "I had to finish a five-course meal that my mom sent me home with." },
    { "id": 552, "excuse": "I forgot my umbrella and had to wait for the rain to stop." },
    { "id": 553, "excuse": "I had to figure out why my light bulb was flickering, and it took forever." },
    { "id": 554, "excuse": "I lost track of time while doing absolutely nothing important." },
    { "id": 555, "excuse": "I was too busy trying to teach my goldfish how to swim faster." },
    { "id": 556, "excuse": "I got stuck in a virtual meeting loop and couldn't escape." },
    { "id": 557, "excuse": "I couldn’t find my shoes, so I had to spend an hour looking for them." },
    { "id": 558, "excuse": "My phone died, and I spent the day trying to charge it with creative methods." },
    { "id": 559, "excuse": "I had to work on my secret plan to organize my sock drawer." },
    { "id": 560, "excuse": "I was busy explaining quantum physics to my cat." },
    { "id": 561, "excuse": "I accidentally turned off my alarm in my sleep." },
    { "id": 562, "excuse": "My mirror told me I looked too good to leave the house today." },
    { "id": 563, "excuse": "I got into an argument with my reflection and had to resolve it before leaving." },
    { "id": 564, "excuse": "I had to make a last-minute costume change for a spontaneous superhero convention." },
    { "id": 565, "excuse": "I thought it was too early to be productive today, so I took a nap instead." },
    { "id": 566, "excuse": "My GPS led me into a dead-end street, so I had to wait for it to recalculate." },
    { "id": 567, "excuse": "I was busy practicing my superhero poses in front of the mirror." },
    { "id": 568, "excuse": "I had to fix my chair because it was on the verge of a meltdown." },
    { "id": 569, "excuse": "I got distracted by a cool cloud formation and had to admire it." },
    { "id": 570, "excuse": "I had to check the weather forecast just to make sure I wasn't living in the upside-down." },
    { "id": 571, "excuse": "I was busy watching a nature documentary about sloths." },
    { "id": 572, "excuse": "I spent too much time wondering how many socks disappear in the laundry." },
    { "id": 573, "excuse": "I couldn't leave because I was waiting for a text from an important person (my mom)." },
    { "id": 574, "excuse": "I spent the day reorganizing my junk drawer." },
    { "id": 575, "excuse": "I had to rescue my dog from a stuck position in the backyard." },
    { "id": 576, "excuse": "I was watching an intense video on how to fold fitted sheets." },
    { "id": 577, "excuse": "I got distracted by a paperclip that was mysteriously bent out of shape." },
    { "id": 578, "excuse": "I was busy refilling the salt shaker because I can't live without extra seasoning." },
    { "id": 579, "excuse": "I couldn't find my shoes and had to search the entire house." },
    { "id": 580, "excuse": "I was talking to my pet about their plans for the weekend." },
    { "id": 581, "excuse": "I was waiting for the perfect alignment of the stars to leave the house." },
    { "id": 582, "excuse": "I spent the morning waiting for my laundry to finish drying." },
    { "id": 583, "excuse": "I had to test out a new recipe that I found online." },
    { "id": 584, "excuse": "My pet hamster ran away and I had to track it down." },
    { "id": 585, "excuse": "I spent the day rearranging my furniture because I was feeling too comfortable." },
    { "id": 586, "excuse": "I had to fix my hair because it was looking too fabulous to be seen in public." },
    { "id": 587, "excuse": "I thought I had more time to get ready but realized it was already time to go." },
    { "id": 588, "excuse": "I had a sudden urge to reorganize my spice rack." },
    { "id": 589, "excuse": "I couldn't leave the house because I was too busy trying to find the perfect pair of socks." },
    { "id": 590, "excuse": "I got stuck in an intense staring contest with my laundry basket." },
    { "id": 591, "excuse": "I was making a crucial decision about what to eat for lunch and got caught in the moment." },
    { "id": 592, "excuse": "I accidentally locked myself in the pantry and had to call for help." },
    { "id": 593, "excuse": "I couldn't leave because my favorite TV show had a cliffhanger." },
    { "id": 594, "excuse": "I was having an existential crisis about my favorite ice cream flavor." },
    { "id": 595, "excuse": "I lost track of time while counting the number of coffee mugs in my kitchen." },
    { "id": 596, "excuse": "I had to finish my online shopping because my cart was about to expire." },
    { "id": 597, "excuse": "I had to finish watching a tutorial on how to fold a fitted sheet." },
    { "id": 598, "excuse": "I got lost on my way out and ended up in the wrong neighborhood." },
    { "id": 599, "excuse": "I was busy meditating to achieve inner peace." },
    { "id": 600, "excuse": "I spent the day trying to teach my dog to do the laundry." },



    //----------Developers--------

        { "id": 601, "excuse": "Oh, sorry, I just put a casserole in the oven." },
        { "id": 602, "excuse": "I got some plastic surgery enhancement done, but it needs a little tweaking to get right." },
        { "id": 603, "excuse": "I sat in the bathroom too long and my legs and feet fell asleep, so when I finally stood up, I fell over and broke my ankle." },
        { "id": 604, "excuse": "It was a big casino weekend for me, so imagine my surprise that I still had some money left to play with on Monday morning." },
        { "id": 605, "excuse": "I woke up in such a good mood that I didn't want to ruin it." },
        { "id": 606, "excuse": "Sorry, I got lucky last night, but I woke up and have no idea where I am." },
        { "id": 607, "excuse": "I was taking my blood pressure with the machine at the grocery store and got stuck and couldn't get out." },
        { "id": 608, "excuse": "I've got a gallstone and am trying to heal it holistically." },
        { "id": 609, "excuse": "My uniform was still wet, so I put it in the microwave to dry and it caught on fire." },
        { "id": 610, "excuse": "Really sorry, but I accidentally got on a plane and I'm not in town." },
        { "id": 611, "excuse": "I'm on the moon and coming back to the sun." },
        { "id": 612, "excuse": "Yesterday, the date was supposed to be 30th February so the whole day, I was figuring out the calendar." },
        { "id": 613, "excuse": "The earth stopped revolving yesterday, so I got freezed at one place." },
        { "id": 614, "excuse": "I was walking on a tightrope and lost my balance." },
        { "id": 615, "excuse": "I had to rescue my breakfast from the cat." },
        { "id": 616, "excuse": "I forgot to set the alarm clock, so I overslept." },
        { "id": 617, "excuse": "My shoes broke and I had to walk barefoot." },
        { "id": 618, "excuse": "I accidentally stepped on a Lego and had to recover." },
        { "id": 619, "excuse": "My neighbor’s cat was in my yard and I was busy negotiating with it." },
        { "id": 620, "excuse": "My watch was stuck on the wrong time zone and I didn’t notice." },
        { "id": 621, "excuse": "I had to stop for a snack because I forgot to eat breakfast." },
        { "id": 622, "excuse": "My internet connection was too slow to get anything done." },
        { "id": 623, "excuse": "I was caught up watching cat videos for hours." },
        { "id": 624, "excuse": "I spent the morning trying to assemble my new furniture." },
        { "id": 625, "excuse": "I was helping my dog with their homework." },
        { "id": 626, "excuse": "I was busy planning my next vacation." },
        { "id": 627, "excuse": "I accidentally locked myself in the bathroom." },
        { "id": 628, "excuse": "I was trying to fix my internet connection, but I made it worse." },
        { "id": 629, "excuse": "I was solving a Rubik’s cube, and it took longer than expected." },
        { "id": 630, "excuse": "I thought it was a weekend today." },
        { "id": 631, "excuse": "I got distracted while trying to catch up on emails." },
        { "id": 632, "excuse": "I spent too much time trying to organize my files." },
        { "id": 633, "excuse": "I accidentally fell into a rabbit hole of YouTube videos." },
        { "id": 634, "excuse": "My morning coffee spilled on my keyboard." },
        { "id": 635, "excuse": "I had to stop for gas and forgot about time." },
        { "id": 636, "excuse": "I had to fight traffic on the way here." },
        { "id": 637, "excuse": "I couldn’t find my car keys, so I was running late." },
        { "id": 638, "excuse": "I was playing video games and lost track of time." },
        { "id": 639, "excuse": "I was dealing with an unexpected home repair." },
        { "id": 640, "excuse": "I had to stop for a much-needed coffee break." },
        { "id": 641, "excuse": "I had to help my neighbor fix their car." },
        { "id": 642, "excuse": "I was too busy staring at my phone screen to realize the time." },
        { "id": 643, "excuse": "I was cleaning out my email inbox." },
        { "id": 644, "excuse": "My computer froze and I had to restart everything." },
        { "id": 645, "excuse": "I was trying to fix my cat’s costume." },
        { "id": 646, "excuse": "I had to chase down a pigeon that stole my lunch." },
        { "id": 647, "excuse": "I was too busy fixing my headphones to hear the time." },
        { "id": 648, "excuse": "I had to figure out why my phone was acting up." },
        { "id": 649, "excuse": "I spent the morning trying to fix my Wi-Fi signal." },
        { "id": 650, "excuse": "I was helping my friend with a baking disaster." },
        { "id": 651, "excuse": "I got distracted by a shiny object on the sidewalk." },
        { "id": 652, "excuse": "I was busy looking for a missing sock." },
        { "id": 653, "excuse": "I got caught up in a deep conversation with my mirror." },
        { "id": 654, "excuse": "My phone was dead, and I had to wait for it to charge." },
        { "id": 655, "excuse": "I was trying to save the last slice of pizza from my dog." },
        { "id": 656, "excuse": "I forgot to set my alarm, and my dog ate my homework." },
        { "id": 657, "excuse": "I was busy trying to remember where I put my keys." },
        { "id": 658, "excuse": "I accidentally left my phone at home, and I had to go back for it." },
        { "id": 659, "excuse": "I couldn’t find my glasses and I was searching everywhere." },
        { "id": 660, "excuse": "I was trapped under a mountain of laundry." },
        { "id": 661, "excuse": "I had to finish a puzzle before I could leave." },
        { "id": 662, "excuse": "I got caught up making a to-do list." },
        { "id": 663, "excuse": "I accidentally ran into a traffic jam caused by a parade." },
        { "id": 664, "excuse": "I was busy waiting for my computer to finish updating." },
        { "id": 665, "excuse": "I got caught up doing some deep philosophical thinking." },
        { "id": 666, "excuse": "I had to finish reading a book that I couldn't put down." },
        { "id": 667, "excuse": "I was stuck in an elevator for longer than expected." },
        { "id": 668, "excuse": "I was fixing a leak and lost track of time." },
        { "id": 669, "excuse": "My Wi-Fi signal was being flaky and I couldn't connect." },
        { "id": 670, "excuse": "I was distracted by a squirrel outside the window." },
        { "id": 671, "excuse": "I couldn't leave because I was busy rearranging the furniture." },
        { "id": 672, "excuse": "I was trying to teach my fish how to swim faster." },
        { "id": 673, "excuse": "I couldn't get out because my phone died in the middle of the process." },
        { "id": 674, "excuse": "I was caught up organizing my comic book collection." },
        { "id": 675, "excuse": "I couldn't find the exit, so I had to backtrack." },
        { "id": 676, "excuse": "I was busy practicing my dance moves." },
        { "id": 677, "excuse": "My dog ate my schedule, so I had to rewrite it." },
        { "id": 678, "excuse": "I got caught up in a deep conversation with Siri." },
        { "id": 679, "excuse": "I was too busy teaching my cat how to fetch." },
        { "id": 680, "excuse": "I was making a playlist for the week and lost track of time." },
        { "id": 681, "excuse": "I had to find a backup charger because my phone was dying." },
        { "id": 682, "excuse": "I got locked out of my own house and couldn't get back in." },
        { "id": 683, "excuse": "I was making soup and it took longer than expected." },
        { "id": 684, "excuse": "I was caught in a sudden hailstorm and had to wait for it to pass." },
        { "id": 685, "excuse": "I was deep in thought, and time just slipped away." },
        { "id": 686, "excuse": "I was looking for the perfect parking spot." },
        { "id": 687, "excuse": "I was too busy being fabulous." },
        { "id": 688, "excuse": "My dog accidentally locked me out of the house." },
        { "id": 689, "excuse": "I was too busy planning my dream vacation." },
        { "id": 690, "excuse": "I was busy making sure my plants were still alive." },
        { "id": 691, "excuse": "I had to finish binge-watching my favorite show." },
        { "id": 692, "excuse": "I had to finish organizing my bookshelf." },
        { "id": 693, "excuse": "I accidentally ate my lunch too fast and had to recover." },
        { "id": 694, "excuse": "I got distracted by a flying balloon." },
        { "id": 695, "excuse": "I accidentally started a new hobby that kept me busy." },
        { "id": 696, "excuse": "I had to find my lost sock, and it took a while." },
        { "id": 697, "excuse": "I was distracted by the rainbow outside." },
        { "id": 698, "excuse": "I was trying to figure out how to fold a fitted sheet." },
        { "id": 699, "excuse": "I was too busy watching the clouds to notice time." },
        { "id": 700, "excuse": "I was working on my top-secret plans for world domination." },



    //----------Gaming--------

        { "id": 701, "excuse": "There is a bug in this code, but I don't know which bug I'm talking about." },
        { "id": 702, "excuse": "The coffee machine stopped working today!" },
        { "id": 703, "excuse": "I don't know how to turn coffee into code." },
        { "id": 704, "excuse": "My friend told me that there's no place like 127.0.0.1 so I went to see if there exists such place." },
        { "id": 705, "excuse": "It works on my machine." },
        { "id": 706, "excuse": "When someone asked me about my blood group, I told him that I'm a code blooded person." },
        { "id": 707, "excuse": "HR asked me why you are late, I told her that I'm an ID." },
        { "id": 708, "excuse": "My aunt told me to fix her computer, so I got late today." },
        { "id": 709, "excuse": "I got cursed because someone reviewed my code." },
        { "id": 710, "excuse": "I was told to declare a war, but I only know how to declare variables." },
        { "id": 711, "excuse": "It's not a bug, it's a feature." },
        { "id": 712, "excuse": "My wifi wasn't working, so I went to find a hot-spot i.e Sun" },
        { "id": 713, "excuse": "We are not in the same version, hence there is a conflict." },
        { "id": 714, "excuse": "I don't know how to code in python, I was hired because, python is in my horoscope." },
        { "id": 715, "excuse": "It must be a hardware issue, not my code problem." },
        { "id": 716, "excuse": "The code was running fine until I looked at it." },
        { "id": 717, "excuse": "The system crashed because it couldn't handle my awesomeness." },
        { "id": 718, "excuse": "I can't debug while I'm too busy contemplating the meaning of life." },
        { "id": 719, "excuse": "My IDE just started talking to me, and I got distracted." },
        { "id": 720, "excuse": "The coffee was too strong; it took me a while to recalibrate." },
        { "id": 721, "excuse": "My code works in theory, but it needs more caffeine to function in reality." },
        { "id": 722, "excuse": "I accidentally deleted the wrong file, but I don't want to talk about it." },
        { "id": 723, "excuse": "I couldn't work because the Wi-Fi kept asking me for the password." },
        { "id": 724, "excuse": "I was debugging my dog, not the code." },
        { "id": 725, "excuse": "I thought I was writing Python, but I accidentally wrote a haiku instead." },
        { "id": 726, "excuse": "I was busy fixing a bug in my lunch instead of my code." },
        { "id": 727, "excuse": "I was waiting for the new version of JavaScript to come out." },
        { "id": 728, "excuse": "I was refactoring my mental state." },
        { "id": 729, "excuse": "My computer has an existential crisis and refuses to run the code." },
        { "id": 730, "excuse": "My system crashed because I tried to run too many good ideas at once." },
        { "id": 731, "excuse": "I was busy trying to explain recursion to my cat." },
        { "id": 732, "excuse": "I had to debug my life before debugging the code." },
        { "id": 733, "excuse": "The code was a piece of art, so I had to admire it for a while." },
        { "id": 734, "excuse": "My version control system ate my progress." },
        { "id": 735, "excuse": "I accidentally cloned myself and got confused between the two." },
        { "id": 736, "excuse": "I was stuck in a JavaScript callback hell." },
        { "id": 737, "excuse": "I was busy setting up my development environment in my dream." },
        { "id": 738, "excuse": "The keyboard wasn't working, but I still wrote code with my mind." },
        { "id": 739, "excuse": "I was busy updating my status to 'I'm debugging.'" },
        { "id": 740, "excuse": "My coffee code failed, and I needed a quick patch." },
        { "id": 741, "excuse": "The server went down because it couldn’t handle my genius." },
        { "id": 742, "excuse": "I forgot to push my code because I was busy pushing my limits." },
        { "id": 743, "excuse": "My monitor is too good at showing errors, so I just stare at it." },
        { "id": 744, "excuse": "I was busy improving the internet, so I was offline for a while." },
        { "id": 745, "excuse": "My compiler needed a coffee break." },
        { "id": 746, "excuse": "I tried to explain the bug to my computer, but it refused to listen." },
        { "id": 747, "excuse": "I was fixing a bug in my code that doesn't even exist." },
        { "id": 748, "excuse": "The debugger was too slow, so I went for a walk instead." },
        { "id": 749, "excuse": "I tried to reprogram my brain to understand the code." },
        { "id": 750, "excuse": "My laptop went on strike, so I had to negotiate with it." },
        { "id": 751, "excuse": "I couldn’t find the right syntax for a good excuse." },
        { "id": 752, "excuse": "The internet kept trying to buffer my thoughts." },
        { "id": 753, "excuse": "My computer got jealous of my phone, so it stopped working." },
        { "id": 754, "excuse": "I ran into an infinite loop of procrastination." },
        { "id": 755, "excuse": "The cloud couldn't handle my brilliance." },
        { "id": 756, "excuse": "I got lost in my code and needed a map." },
        { "id": 757, "excuse": "I was updating my LinkedIn profile to reflect my new status as a professional procrastinator." },
        { "id": 758, "excuse": "I accidentally wrote a script to take over the world, so I had to fix it." },
        { "id": 759, "excuse": "I was writing a comment in the code, and it took too long to explain the logic." },
        { "id": 760, "excuse": "The server needed me to perform some emotional support." },
        { "id": 761, "excuse": "I was too busy updating my memes instead of the code." },
        { "id": 762, "excuse": "My code was written in cursive, and it was hard to read." },
        { "id": 763, "excuse": "I tried to fix the bug, but the bug fixed me." },
        { "id": 764, "excuse": "My keyboard got jealous of my mouse and decided to stop working." },
        { "id": 765, "excuse": "I forgot to commit because I was busy committing to my break." },
        { "id": 766, "excuse": "I ran out of coffee before I could finish the code." },
        { "id": 767, "excuse": "My monitor was displaying an error, but I couldn’t read it because of my artistic vision." },
        { "id": 768, "excuse": "The server crashed after it saw my brilliant code." },
        { "id": 769, "excuse": "I was debugging my lunch because it wasn’t working either." },
        { "id": 770, "excuse": "I couldn't solve the problem because my brain was buffering." },
        { "id": 771, "excuse": "My IDE had a meltdown when I tried to run my idea." },
        { "id": 772, "excuse": "I got distracted by a cat video and couldn’t fix the code." },
        { "id": 773, "excuse": "My computer froze because it couldn't handle my genius." },
        { "id": 774, "excuse": "I got caught in a web of JavaScript." },
        { "id": 775, "excuse": "The code was too perfect, so the universe had to interfere." },
        { "id": 776, "excuse": "My program refused to work because it knew I was about to take a nap." },
        { "id": 777, "excuse": "I was busy attending an impromptu meeting with the coffee machine." },
        { "id": 778, "excuse": "My computer wouldn’t start because it was waiting for my mental reboot." },
        { "id": 779, "excuse": "I had to consult with my pet hamster before making any changes." },
        { "id": 780, "excuse": "The code only works on alternate Tuesdays." },
        { "id": 781, "excuse": "I was analyzing the code's aura before fixing the bugs." },
        { "id": 782, "excuse": "I was busy sorting out my priorities, starting with Netflix." },
        { "id": 783, "excuse": "I was busy creating a digital version of myself to handle the tasks." },
        { "id": 784, "excuse": "I had to restart my computer because it couldn't handle my awesomeness." },
        { "id": 785, "excuse": "I tried to fix the bug, but it came back with a vengeance." },
        { "id": 786, "excuse": "I got distracted by the endless possibilities of open tabs." },
        { "id": 787, "excuse": "I was too busy writing cryptic comments in my code." },
        { "id": 788, "excuse": "I tried to program a solution, but I accidentally programmed a disaster." },
        { "id": 789, "excuse": "I tried to code, but I got lost in the rabbit hole of StackOverflow." },
        { "id": 790, "excuse": "My code runs fine, but it’s running on dreams and caffeine." },
        { "id": 791, "excuse": "I had to take a break because my computer kept throwing exceptions." },
        { "id": 792, "excuse": "I didn’t code the bug in; it was just a feature waiting to be discovered." },
        { "id": 793, "excuse": "I was debugging my cat's behavior instead of the code." },
        { "id": 794, "excuse": "The problem is that the computer doesn't understand my creative genius." },
        { "id": 795, "excuse": "I thought I was coding, but I was just daydreaming." },
        { "id": 796, "excuse": "My code is like an art piece, it needs time to appreciate." },
        { "id": 797, "excuse": "I had to pause the coding because I was thinking too deeply about the meaning of life." },
        { "id": 798, "excuse": "I couldn’t finish it because I was trying to solve the meaning of recursion." },
        { "id": 799, "excuse": "I couldn't commit because I was too busy committing to the wrong branch." },
        { "id": 800, "excuse": "My code worked, but my computer was in denial." },
];
